### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by Mynothian** [iChun/IssueTracker-GravityGun#9]
OS: Mac v. 10.6.8
Forge Version: 10.13.2.1291
Minecraft Version: 1.7.10

Each time I attempt to launch Minecraft with your Gravity Gun mod, the game crashes. The game claims that a "IPlayerTracker" class is missing. I have never gotten this mod to run correctly, hope you can help solve this issue.

**Comment by iChun** [comment]
http://ichun.us/support/faq/mods/

**Comment by Mynothian** [comment]
Even with the forge version for 1.6.4, it refuses to launch.

**Comment by iChun** [comment]
Are you still trying to run it on MC 1.7.10?

**Comment by Mynothian** [comment]
Yes.

**Comment by iChun** [comment]
Why are you trying to run Forge 1.6.4 on MC 1.7.10?
